# update_fastlane

default_platform(:android)

platform :android do
  desc "Run static analysis, unit tests, and integration tests and a dev-flavor apk build"
  lane :validate_pr do
    flutter_root = File.expand_path("../..", __dir__)
    Dir.chdir(flutter_root) do
      sh("flutter pub get")
      sh("flutter analyze")
      sh("flutter test")
      sh("flutter build apk --flavor dev -t lib/main_dev.dart")

    end
  end
end

  desc "build the release appbundle and upload to firebase app distribution"
  lane :distribute_release_to_firebase do
    flutter_root = File.expand_path("../..", __dir__)
    Dir.chdir(flutter_root) do
      sh("flutter pub get")
      sh("flutter build appbundle --flavor dev -t lib/main_dev.dart")
    end
    firebase_app_distribution(
      app: "1:624493250471:android:1d207c334afad203405882",
      firebase_cli_token: ENV.fetch("FIREBASE_CLI_TOKEN"),
      groups: "testers",
      android_artifact_path: "../build/app/outputs/bundle/devRelease/app-dev-release.aab",
  end
end

